import { readFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ReviewData, LineAnnotation } from '@acr/shared';
import { findingsFile, sessionId, saveDir } from './config';
export function readFindings(): ReviewData {
  try { return JSON.parse(readFileSync(findingsFile, 'utf8')); }
  catch {
    return { verdict: '', findings: [], files: [], summary: '',
             timestamp: new Date().toISOString(), branch: '', sessionId };
  }
}

function ensureDir(dir: string) { if (!existsSync(dir)) mkdirSync(dir, { recursive: true }); }

export function saveMarkdown(
  data: ReviewData & { _decision?: any },
  lineAnnotations?: Record<string, LineAnnotation>
): string {
  ensureDir(saveDir);
  const date = new Date().toISOString().slice(0, 10);
  const branch = (data.branch || 'unknown').replace(/[^a-z0-9_-]/gi, '-');
  const filepath = join(saveDir, `${date}-${branch}.md`);

  const groups: Record<string, any[]> = { CRITICAL: [], HIGH: [], NOTE: [] };
  for (const f of data.findings || []) {
    const sev = (f.severity || 'NOTE').toUpperCase();
    (groups[sev] || groups.NOTE).push(f);
  }
  const decision = data._decision || {};
  const selectedIds = new Set<string>(decision.selectedIds || []);
  const comments: Record<string, string> = decision.comments || {};
  const globalComment: string = decision.globalComment || '';

  let md = `# Code Review — ${date} (branch: ${data.branch || 'unknown'})\n\n`;
  md += `**Verdict:** ${data.verdict || '_No verdict_'}\n\n`;
  if (globalComment) md += `> **Your notes:** ${globalComment}\n\n`;

  for (const [sev, items] of Object.entries(groups)) {
    md += `## ${sev}\n\n`;
    if (!items.length) { md += '_None._\n\n'; continue; }
    for (const f of items) {
      const status = selectedIds.has(f.id) ? '☑ selected for implementation' : '☐ not selected';
      md += `- **${f.location || f.file}** — ${f.finding}\n`;
      if (f.reasoning) md += `  - Reasoning: ${f.reasoning}\n`;
      if (f.evidence) md += `  - Evidence: \`${f.evidence}\`\n`;
      if (f.dimensions?.length) md += `  - Dimensions: ${f.dimensions.join(', ')}\n`;
      md += `  - Status: ${status}\n`;
      if (comments[f.id]) md += `  - Your comment: "${comments[f.id]}"\n`;
      md += '\n';
    }
  }
  md += `## Summary\n\n${data.summary || ''}\n\n`;

  const annots = lineAnnotations || {};
  const keys = Object.keys(annots);
  if (keys.length) {
    md += `## Line Annotations\n\n`;
    for (const k of keys) {
      const a = annots[k];
      md += `- **${a.file}** lines ${a.lineStart}–${a.lineEnd} (${a.side}): [${a.type}] ${a.text}\n`;
    }
    md += '\n';
  }
  md += `---\n_Generated by agentic-code-reviewer_\n`;
  writeFileSync(filepath, md, 'utf8');
  return filepath;
}
